---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: document
  path: src/index.md
  label: Home
- type: document
  path: src/jack.md
  label: Jack
- type: document
  path: src/faq.md
  label: FAQ
- type: directory
  path: src/blog
  label: Posts
  create: all
  match: "**/*"
upload_dir: src/.vuepress/public/images
public_path: images
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: ".vuepress/dist"
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run dev
